services:
  mysql:
    image: mysql:latest
    container_name: mysql-msresident
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: msresident
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-msresident
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
