version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-msaccesscontrol
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: msaccesscontrol
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-msaccesscontrol
    environment:
      PMA_HOST: mysql-msaccesscontrol
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
